<?php
namespace Assimp\Tests\Command\Verbs\Container;

use Assimp\Command\Verbs\Container\ParameterContainer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-26 at 12:23:35.
 */
class ParameterContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ParameterContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ParameterContainer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::get
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::set
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::add
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::has
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::all
     * @todo   Implement testGet().
     */
    public function testGetSetAddHas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }


    /**
     * @covers Assimp\Command\Verbs\Container\ParameterContainer::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
