<?php
namespace Assimp\Tests\Command;

use Assimp\Command\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-26 at 12:17:21.
 */
class CommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Command
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Command();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Assimp\Command\Command::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Assimp\Command\Command::getBinary
     */
    public function testGetBinary()
    {
        $this->assertEquals('/usr/bin/assimp', $this->object->getBinary());
    }

    /**
     * @covers Assimp\Command\Command::setBinary
     */
    public function testSetBinarySuccess()
    {
        $this->assertInstanceOf('\Assimp\Command\Command', $this->object->setBinary('/usr/bin/assimp'));
    }

    /**
     * @covers Assimp\Command\Command::setBinary
     * @expectedException \InvalidArgumentException
     */
    public function testSetBinaryFailure()
    {
        $this->object->setBinary('/usr/local/bin/assimp');
    }
}
